### ISSUE TITLE
GetBibEntryWithDOI error

### ISSUE THREAD

**Issue by sghignone** [ropensci/RefManageR#93] opened 2021-12-20 16:13 UTC
What's the meaning of the error message I get with some DOI I'm working with, e.g.
`GetBibEntryWithDOI(doi = "10.1016/j.jflm.2021.102223") `
`GetBibEntryWithDOI(doi = "10.1111/1462-2920.15688")`
for both I get:
`Error in substring(u, so, so + ml - 1L) : 
  invalid multibyte string, element 1`

Might this be related to UTF-8 encoding, as reported [here](https://stackoverflow.com/questions/60906507/how-to-solve-error-error-in-ncharrownamesm-invalid-multibyte-string-ele)?

In fact, some authors' surname have special characters (accented chars)...

I'm using 
packageVersion('RefManageR')
[1] ‘1.3.5’
and
packageVersion('bibtex')
[1] ‘0.4.3’

**Comment by sghignone** [comment] 2021-12-23 14:38
I also verified that GetBibEntryWithDOI does not retrieve _keywords_ nor _abstract_, even when they are present in bib files downloaded from publisher website. Is it possible to have those fields included in the query?

**Comment by ChristopherBarrington** [comment] 2022-02-17 11:04
I have the same problem described above (sorry, I can't help though!):

```r
> RefManageR::GetBibEntryWithDOI(doi='10.1038/s41559-018-0575-6')
Error in substring(u, so, so + ml - 1L) :
  invalid multibyte string, element 1
> packageVersion('RefManageR')
[1] ‘1.3.5’
> packageVersion('bibtex')
[1] ‘0.4.2.3’
```

This DOI will get you to the correct publication.

**Comment by nicocriscuolo** [comment] 2022-06-22 08:25
I am also experiencing the same problem. It doesn't happen with all DOIs, but with some of them. I inspected the function, and the problem occurs inside the `GET()` function.

A feedback would be much appreciated. Thanks!

**Comment by mwmclean** [comment] 2022-06-27 05:48
I've tried three different versions of R: 3.6, 4.0, 4.2 (the only one with native UTF-8 support) and I can't reproduce this error on my Windows 10 machine for any of the examples in this thread. Can you please share a reproducible example and your `sessionInfo()` @nicocriscuolo?

**Comment by nicocriscuolo** [comment] 2022-06-27 08:23
Hi @mwmclean and thank you for your answer. I tried to reproduce the error with the following code:

```R
library(RefManageR)

GetBibEntryWithDOI(doi = "10.1126/science.aaw1944")
```

And here's my sessionInfo() data:

```R
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RefManageR_1.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3     xml2_1.3.3       magrittr_2.0.3   tidyselect_1.1.2 R6_2.5.1         rlang_1.0.2      bibtex_0.4.2.3  
 [8] fansi_1.0.3      stringr_1.4.0    httr_1.4.3       plyr_1.8.7       dplyr_1.0.9      tools_4.2.0      utf8_1.2.2      
[15] cli_3.3.0        DBI_1.1.2        ellipsis_0.3.2   assertthat_0.2.1 tibble_3.1.7     lifecycle_1.0.1  crayon_1.5.1    
[22] purrr_0.3.4      vctrs_0.4.1      curl_4.3.2       glue_1.6.2       stringi_1.7.6    compiler_4.2.0   pillar_1.7.0    
[29] generics_0.1.2   jsonlite_1.8.0   lubridate_1.8.0  pkgconfig_2.0.3
```

However, this morning everything was working correctly. I tested this function on different machines and everything was fine. Is it possible that this error was just temporarily? Thanks

**Comment by mwmclean** [comment] 2024-10-23 11:22
Closing until further reprexes/`sessionInfo`'s come in as I'm still unable to reproduce this.

**Closed by mwmclean** 2024-10-23 11:22 UTC
